/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-02-04 04:45:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.boardsearch;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>게시판</title>\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("  <script src=\"http://localhost/boardpro/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <script src=\"../js/boardsearch.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body{\r\n");
      out.write("\tbackground : pink;\r\n");
      out.write("\tpadding : 20px;\r\n");
      out.write("}\r\n");
      out.write(".box{\r\n");
      out.write("\tpadding : 10px;\r\n");
      out.write("}\r\n");
      out.write(".card-header{\r\n");
      out.write("\tbackground : lightblue;\r\n");
      out.write("\tmargin : 2px;\r\n");
      out.write("}\r\n");
      out.write(".card-header:hover{\r\n");
      out.write("\tbackground : maroon;\r\n");
      out.write("}\r\n");
      out.write(".pagination{\r\n");
      out.write("\tfloat : left;\r\n");
      out.write("}\r\n");
      out.write("#btngroup1{\r\n");
      out.write("\tmargin-left : 45%;\r\n");
      out.write("}\r\n");
      out.write("input[name=reply]{\r\n");
      out.write("\theight: 55px;\r\n");
      out.write("\tvertical-align: top;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("nav{\r\n");
      out.write("\tbackground : lightblue;\r\n");
      out.write("}\r\n");
      out.write("#stype{\r\n");
      out.write("\twidth : 100px; \r\n");
      out.write("}\r\n");
      out.write(".rep{\r\n");
      out.write("\tborder : 1px solid gray;\r\n");
      out.write("\tbackground : #ffd699;\r\n");
      out.write("\tmargin : 1px;\r\n");
      out.write("\tpadding : 3px;\r\n");
      out.write("}\r\n");
      out.write(".p1{\r\n");
      out.write("   width : 60%;\r\n");
      out.write("   float : left;   \r\n");
      out.write("   border : none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".p2{\r\n");
      out.write("   width : 38%;\r\n");
      out.write("   float : left; \r\n");
      out.write("   text-align: right;\r\n");
      out.write("   border : none;  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("hr{\r\n");
      out.write("   clear : both;   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#modifyform{\r\n");
      out.write("\tdisplay : none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("reply = {};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\t// js/boardserach.js에 구현\r\n");
      out.write("\tlistServer(1);\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t// 이벤트\r\n");
      out.write("\t// 수정, 삭제, 등록, 댓글 등록, 댓글 수정, 댓글 삭제, 제목(list)버튼에 대한 이벤트\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".box\").on(\"click\", \".action\", function(){\r\n");
      out.write("\t\tactionName = $(this).attr(\"name\");\r\n");
      out.write("\t\tactionIdx = $(this).attr(\"idx\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(actionName == \"modify\"){\r\n");
      out.write("\t\t\talert(actionIdx + \"번 글을 수정합니다.\");\r\n");
      out.write("\t\t}else if(actionName == \"delete\"){\r\n");
      out.write("\t\t\talert(actionIdx + \"번 글을 삭제합니다.\");\t\t\t\r\n");
      out.write("\t\t}else if(actionName == \"reply\"){\t\t\t\r\n");
      out.write("\t\t\t// 입력한 내용 가져오기\r\n");
      out.write("\t\t\tcont = $(this).prev().val();\r\n");
      out.write("\t\t\t// 저장할 요소를 만들기 - renum, bonum, name, cont, redate\r\n");
      out.write("\t\t\treply.bonum = actionIdx;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tname1 = String.fromCharCode(Math.random() * 26 + 65);\r\n");
      out.write("\t\t\tname2 = String.fromCharCode(Math.random() * 26 + 97);\r\n");
      out.write("\t\t\tname3 = parseInt(Math.random() * 100 + 1);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treply.name = name1 + name2 + name3;\r\n");
      out.write("\t\t\treply.cont = cont;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(this).prev().val(\"\"); // 댓글  지우기 \r\n");
      out.write("\t\t\t// boardsearch.js의 replyInsert()실행\r\n");
      out.write("\t\t\treplyInsert(this); // 댓글 저장\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 댓글 리스트( 비동기 방식에서는 응답이 섞일 수도 있다. 따라서 확실히 응답을 받고나서 댓글조회를 요청한다. \r\n");
      out.write("\t\t\t//\t\tboardsearch.js의 success에서 기술 )\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t}else if(actionName == \"r_modify\"){\r\n");
      out.write("\t\t\talert(actionIdx + \"번 댓글을 수정합니다.\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 댓글 수정폼 modifyform의 display 스타일속성값을 가져온다.\r\n");
      out.write("\t\t\t// none이 아니면 - 보여지고 있는 상태 : 다른 곳에 수정폼이 열려있다면, 보여지고 있는 수정폼을 닫는다.\r\n");
      out.write("\t\t\tif($(\"#modifyform\").css(\"display\") != \"none\"){\r\n");
      out.write("\t\t\t\treplyReset();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 수정할 내용을 가져오기\r\n");
      out.write("\t\t\tmodifycont = $(this).parents(\".rep\").find(\".p3\").html();\r\n");
      out.write("\t\t\t// br태그를 \\n으로 바꿔준다.\r\n");
      out.write("\t\t\tmodifycont = modifycont.replace(/<br>/g, \"\\n\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 수정할 내용(원래글)을 수정폼에 modifyform에 출력하기\r\n");
      out.write("\t\t\t$(\"#modifyform #text\").val(modifycont);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 수정폼을 보이게 하기\r\n");
      out.write("\t\t\t$(this).parents(\".rep\").find(\".p3\").empty().append($(\"#modifyform\"));\r\n");
      out.write("\t\t\t$(\"#modifyform\").css(\"display\", \"block\");\r\n");
      out.write("\t\t\t// $(\"#modifyform\").show(); : J쿼리 메서드 사용\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}else if(actionName == \"r_delete\"){\r\n");
      out.write("\t\t\talert(actionIdx + \"번 댓글을 삭제합니다.\");\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// DB삭제\r\n");
      out.write("\t\t\treplyDelete(this);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}else if(actionName == \"list\"){\t\t\t\r\n");
      out.write("\t\t\treplyList(this);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t// 댓글 수정창 닫기\r\n");
      out.write("\treplyReset = function(){\r\n");
      out.write("\t\tcp3 = $(\"#modifyform\").parent();\r\n");
      out.write("\t\tcp3value = $(\"#modifyform #text\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"body\").append($(\"#modifyform\"));\r\n");
      out.write("\t\t$(\"#modifyform\").hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcp3value = modifycont.replace(/\\n/g,\"<br>\");\r\n");
      out.write("\t\tcp3.html(cp3value);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t// page번호 : pnum 이벤트\r\n");
      out.write("\t$(\"#btngroup1\").on(\"click\", \".pnum\", function(){\r\n");
      out.write("\t\tnumtext = $(this).text().trim();\r\n");
      out.write("\t\tcurrentPage = numtext;\r\n");
      out.write("\t\tlistServer(currentPage);\r\n");
      out.write("\t})\r\n");
      out.write("\t// 다음\r\n");
      out.write("\t$(\"#btngroup1\").on(\"click\", \".next\", function(){\r\n");
      out.write("\t\tnextnum = parseInt($(\".pager a\").last().text().trim()) +1;\r\n");
      out.write("\t\tcurrentPage = nextnum;\r\n");
      out.write("\t\tlistServer(currentPage);\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t// 이전\r\n");
      out.write("\t$(\"#btngroup1\").on(\"click\", \".previous\", function(){\r\n");
      out.write("\t\tnextnum = parseInt($(\".pager a\").first().text().trim()) -1;\r\n");
      out.write("\t\tcurrentPage = nextnum;\r\n");
      out.write("\t\tlistServer(currentPage);\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t// 검색버튼\r\n");
      out.write("\t$(\"#search\").on(\"click\", function(){\r\n");
      out.write("\t\tlistServer(1);\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t// 댓글 수정창에서 수정버튼 클릭\r\n");
      out.write("\t$(\"#btnreset\").on(\"click\", function(){\r\n");
      out.write("\t\treplyReset();\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t// 댓글 수정창에서 확인버튼 클릭\r\n");
      out.write("\t$(\"#btnok\").on(\"click\", function(){\r\n");
      out.write("\t\talert(actionIdx);\r\n");
      out.write("\t\t// 수정한 내용을 가져오기\r\n");
      out.write("\t\tmodifycont = $(\"#modifyform #text\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcp3 = $(\"#modifyform\").parent();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 수정폼을 body로 이동 - 감추기\r\n");
      out.write("\t\t$(\"body\").append($(\"#modifyform\"));\r\n");
      out.write("\t\t$(\"#modifyform\").hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 수정내용의 \\n을 <br>태그로 변경\r\n");
      out.write("\t\t modifycont2 = modifycont.replace(/\\n/g,\"<br>\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t// 수정항목을 DB로 보내기 - js\r\n");
      out.write("\t\treplyUpdate(); // renum이랑 cont필요\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// p3에 수정내용 출력 (화면에서만 수정됨)\r\n");
      out.write("\t\t// cp3.html(modifycont);\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"modifyform\">\r\n");
      out.write("\t\t<textarea rows=\"5\" cols=\"50\" id=\"text\"></textarea>\r\n");
      out.write("\t\t<input type=\"button\" value=\"확인\" id=\"btnok\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"취소\" id=\"btnreset\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-sm \">\r\n");
      out.write("\t<select id=\"stype\" class=\"form-control\">\r\n");
      out.write("\t\t<option value=\"\">전체</option>\r\n");
      out.write("\t\t<option value=\"subject\">제목</option>\r\n");
      out.write("\t\t<option value=\"content\">내용</option>\r\n");
      out.write("\t\t<option value=\"writer\">작성자</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("    <form class=\"form-inline\">\r\n");
      out.write("    \t<input id=\"sword\" class=\"form-control mr-sm-2\" type=\"text\" placeholder=\"Search\">\r\n");
      out.write("    \t<button id=\"search\" class=\"btn btn-success\" type=\"button\">Search</button>\r\n");
      out.write("    </form>\r\n");
      out.write("</nav>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div class=\"box\"></div>\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\t<div id=\"btngroup1\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<!-- The Modal -->\r\n");
      out.write("<div class=\"modal\" id=\"modifyModal\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal Header -->\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">Modal Heading</h4>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal body -->\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <form action=\"\">\r\n");
      out.write("        \t<label>제목</label><input type=\"text\" name=\"subject\"><br>\r\n");
      out.write("        \t<label>이름</label><input type=\"text\" name=\"writer\"><br>\r\n");
      out.write("        \t<label>메일</label><input type=\"text\" name=\"mail\"><br>\r\n");
      out.write("        \t<label>비밀번호</label><input type=\"password\" name=\"password\"><br>\r\n");
      out.write("        \t<label>내용</label><textarea cols=\"30\" rows=\"50\"></textarea>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal footer -->\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
